name: CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ staging ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./src/ripper_wasm   

jobs:
  rust:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: cargo build --verbose

    - name: Build npm wasm package
      run: wasm-pack build

    - name: Cargo test
      run: cargo test

    - name: Wasm-pack test
      run: wasm-pack test --node
