# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/        

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Build npm wasm package
      run: wasm-pack build
      working-directory: ./src/ripper_wasm
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}      
           
    - name: Npm symlink
      run: sudo npm link
      working-directory: ./src/ripper_wasm/pkg
      
    - name: Npm link wasm package
      run: npm link rust_ripper_wasm
      working-directory: ./src/site
      
    - name: Install dependencies
      run: npm install
      working-directory: ./src/site
    
    - name: Pack site
      run: npm run build
      working-directory: ./src/site
    - run: npm test
