name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.X, 15.x]   

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Build npm wasm package
      run: wasm-pack build
      working-directory: ./src/ripper_wasm
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        script: |
          cd ./src/ripper_wasm/pkg
          sudo npm link
          cd ../../site
          sudo npm link rust_ripper_wasm
          npm install
          npm run build
