name: Rust

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ./src/ripper_wasm

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: cargo test
        working-directory: ./src/ripper_wasm
      - run: wasm-pack test --node
        working-directory: ./src/ripper_wasm

